# ops/docker-compose.yml
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports: ["3306:3306"]
    healthcheck:
      test:
        ["CMD-SHELL", "mysqladmin ping -h localhost -uuser -ppass || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
  redis:
    image: redis:7
    ports: ["6379:6379"]
